JetBrains/lincheck

README.md
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Reporter.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Result.java

Now instead of
> get(1)
> get(2)
>
> 3
> 4
we get
> get(1): 3
> get(2): 4
upon incorrect result

Improve incorrect results representation

---

lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt

Without it some exceptions such as `OutOfMemoryError` are replaced with `NullPointerException` loosing all information about them.
Or when a method with `@Operation` annotation is not public a `NullPointerException` is thrown.

Fixed loss of exception when exception has no cause

---

lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Reporter.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Result.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/Strategy.java
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/ExceptionAsResultTest.java

Output in case of exceptions looked like
```
getOrException(1): Class
```
(i.e. exception name was lost)
Will be
```
getOrException(1): NoSuchElementException
```

Fixed 'Class' instead of exception name in report

---

lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Reporter.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/execution/RandomExecutionGenerator.java
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/AlmostEmptyScenarioTest.kt

Fixed bug with wrong alignment in Reporter

---

lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/CTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/LinChecker.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Options.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Reporter.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchCTest.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchCTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchOptions.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTest.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressOptions.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/quantitative/QuantitativelyRelaxedLinearizabilityContext.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/FailedScenarioMinimizationTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/strategy/randomswitch/RandomSwitchOptionsTest.java
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/strategy/stress/StressOptionsTest.java

A feature to minimise scenarios with incorrect executions so that instead of huge messages like the following one
```
= Invalid execution results: =
Init part:
[put(1, 2): null, put(4, 6): null, get(5): null, put(3, -6): null, put(1, -8): 2]
Parallel part:
| get(4):     6    | put(2, 1):  null |
| get(2):     null | put(5, 4):  null |
| put(5, -8): null | get(3):     -6   |
| get(3):     -6   | get(4):     6    |
| put(3, 5):  -6   | put(1, -4): -8   |
Post part:
[put(5, -8): 4, put(5, -2): -8, get(1): -4, put(2, -8): 1, get(1): -4]
```
we get just a short minimized scenario
```
= Invalid execution results: =
Parallel part:
| put(5, -8): null | put(5, 4): null |
```

Scenario minimization

---

lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/CTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/LinChecker.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/execution/ExecutionGenerator.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/execution/RandomExecutionGenerator.java
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/BufferedChannelStressTest.kt

Allow `actorsAfter` to be greater than 0, so that generators can add a post part if the parallel one does not contain suspendable actors

Allow `actorsAfter` being greater than 0

---

README.md
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/CTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/LinChecker.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Options.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchCTest.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchCTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchOptions.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTest.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressOptions.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/DummySequentialSpecification.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/EpsilonVerifier.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/LTS.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/SerializabilityVerifier.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/Verifier.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/linearizability/LinearizabilityVerifier.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/quantitative/QuantitativelyRelaxedLinearizabilityVerifier.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/quiescent/QuiescentConsistencyVerifier.java
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/SequentialSpecificationTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/quantitative/KPriorityQueueTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/quantitative/KRelaxedPopStack.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/quantitative/KStackTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/quantitative/QuantitativeStackTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/quantitative/StutteringCounterTest.java

Instead of using concurrent implementations sequentially a sequential way as a specification, it is sometimes better to write a simple sequential implementation instead.

Adding sequential specification for verifiers

---

lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Result.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/runner/TestThreadExecutionGenerator.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/LTS.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/linearizability/LinearizabilityVerifier.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/quantitative/QuantitativelyRelaxedLinearizabilityContext.kt
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/quantitative/QuantitativelyRelaxedLinearizabilityVerifier.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/runner/ParallelThreadsRunnerEasyExceptionTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/CustomScenarioDSL.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/BufferedChannelCustomTest.kt
lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/RendezvousChannelCustomTest.kt

`VoidResult` and `NoResult` were singletons with mutable `wasSuspended` parameter. Consequently, both LTS and runner changed this parameter to either `true` or `false` instead of creating immutable instances; this logic caused several bugs, which have been fixed in this pull request. The change makes `wasSuspended` final, and introduces the following singletons: `VoidResult`, `SuspendedVoidResult`, `NoResult`, `Suspended`.

Make `Result` immutable

---

lincheck/pom.xml
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/TransformationClassLoader.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/runner/Runner.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/ManagedStrategy.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/ManagedStrategyTransformer.java
lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/Strategy.java
pom.xml

Changes:
1) Updated version of ASM to 7.1. Now LinCheck can transform classes up to Java 13.
2) Got rid of dependency from Devexperts Bintray  repository.

Updated bytecode transformation dependencies

---

README.md
src/main/java/org/jetbrains/kotlinx/lincheck/CTestConfiguration.java
src/main/java/org/jetbrains/kotlinx/lincheck/CTestStructure.java
src/main/java/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/main/java/org/jetbrains/kotlinx/lincheck/Reporter.kt
src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
src/main/java/org/jetbrains/kotlinx/lincheck/annotations/Validate.kt
src/main/java/org/jetbrains/kotlinx/lincheck/execution/ExecutionScenario.java
src/main/java/org/jetbrains/kotlinx/lincheck/runner/InvocationResult.kt
src/main/java/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/main/java/org/jetbrains/kotlinx/lincheck/runner/Runner.java
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/LincheckFailure.kt
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/ManagedStrategy.java
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchCTestConfiguration.java
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/randomswitch/RandomSwitchStrategy.java
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.java
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressStrategy.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/ValidateFunctionTest.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/runner/ParallelThreadsRunnerEasyExceptionTest.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/runner/TestThreadExecutionHelperTest.java

Add validation mechanism

---

src/main/java/org/jetbrains/kotlinx/lincheck/Actor.kt
src/main/java/org/jetbrains/kotlinx/lincheck/CTestStructure.java
src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
src/main/java/org/jetbrains/kotlinx/lincheck/annotations/Operation.java
src/main/java/org/jetbrains/kotlinx/lincheck/execution/ActorGenerator.kt
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/BlockingOperationTest.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/ClocksTest.kt

Sometimes some operations on the testing data structures are blocking, but it would be great to still be able to test the rest ones for obstruction-freedom.

The obstruction-freedom check should ignore executions with uncompleted blocking operations

---

src/main/java/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/representation/ObstructionFreedomRepresentationTest.kt

It was unclear why obstruction freedom violation happened, because the event that caused it was not reported

The last event that caused obstruction freedom violation should be logged

---

src/main/java/org/jetbrains/kotlinx/lincheck/Actor.kt
src/main/java/org/jetbrains/kotlinx/lincheck/CTestStructure.java
src/main/java/org/jetbrains/kotlinx/lincheck/TransformationClassLoader.java
src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
src/main/java/org/jetbrains/kotlinx/lincheck/annotations/Operation.java
src/main/java/org/jetbrains/kotlinx/lincheck/execution/ActorGenerator.kt
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedCTestConfiguration.kt
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/main/java/org/jetbrains/kotlinx/lincheck/strategy/managed/TracePoint.kt
src/test/java/org/jetbrains/kotlinx/lincheck/test/BlockingBehaviourTest.kt

Split the operations that are blocking by themselves and that cause blocking behavior of concurrent ones

Split blocking operations declaration

---

src/main/java/org/jetbrains/kotlinx/lincheck/CTestStructure.java
src/test/java/org/jetbrains/kotlinx/lincheck/test/ScenarioGenerationParameterDiversityTest.kt

Previously, different parameter generators with the same `Random` seeds were used for all unnamed parameters,
causing `fun operation(a: Int, b: Int, c: Int)` to always have `a == b == c`

Improved scenario generation diversity

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/AbstractLincheckTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/PromptCancellationTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/ConcurrentHashMapTest.kt

Some concurrent structures in `java.util.concurrent` use package-private static methods from `ThreadLocalRandom` that caused illegal access errors in Java 9+

Fixed illegal access with package-private methods in ThreadLocalRandom

---

README.md
src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/LincheckFailure.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedOptions.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TracePoint.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TraceReporter.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingOptions.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/CapturedValueRepresentationTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/MethodReportingTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/SwitchAsFirstMethodEventTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/TraceReportingTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/VerboseTraceTest.kt

When `ModelCheckingOptions.verboseTrace` is set, Lincheck will not try to compress calls without thread context switches.
Moreover, this PR adds tree indentation to the trace, so instead of 
```
= Parallel part execution: =
| put(4, -4)                                                  |                      |
|   table.READ: null at HashMap.putVal(HashMap.java:628)      |                      |
|   table.READ: null at HashMap.resize(HashMap.java:678)      |                      |
|   switch                                                    |                      |
|                                                             | put(-8, -8): null    |
|                                                             |   thread is finished |
|   threshold.READ: 12 at …
```

More verbose trace for managed strategies

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/LTS.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/PromptCancellationTest.kt

Invoking `cancelCompletedResult` method is incorrect with `tryResume` -- it may lead to both completing the suspended coroutine and invoking all the cancellation handlers. See the unit test below that shows the problem:
```
@Test
fun testTryResumeOnCancellation() = runTest {
// Start a new coroutine, suspend it, and store
// the corresponding `CancellableContinuation` instance.
var cont: CancellableContinuation<Unit>? = null
launch {
expect(2)
suspendCancellableCoroutine<Unit> {
cont = it
}
expectUnreached() // <-- IT IS REACHED ACTUALLY!!
}
expect(1)
yield()
expect(3)
// Try to resume the launched coroutine.
var onCancellationInvoked = false  // we expect it to become `true`
val token = cont!!.tryResume(Unit, null) {
onCancellationInvoked = true
}
assertNotNull(token) // assert that …
```

Prompt cancellation should be emulated by cancelling the parent job

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt

`Thread.yield` invocations should not be present in the transformed code in model checking mode, because in the mode the execution is fully managed by model checking strategy.
Leaving `Thread.yield` raises perfomance issues

Thread.yield should be ignored in model checking

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/nvm/RecoverabilityModel.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/verifier/nlr/ReadWriteObjectTest.kt

NRL support single thread crashes. System/single-thread crash choice was done by random(which is deterministic in MC, so the whole iteration may be redundant). It is better to iterate over this choice in MC mode.
I had a falling test on bug search, which failed because of random single thread crash prioritising.
With this fix, bug search time has no visible changes.

Single thread crash in MC

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/FieldInheritedFromInterfaceTest.java

Lincheck failed to transform class with a field that was inherited from an interface.

Fix `NoSuchFieldException` when a field is inherited from an interface

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/Result.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/SerializableValueTests.kt

Fixed a bug in handling `null` results

Handle `null`-s as results properly 

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/WaitNotifyLockTest.kt

Fixed several issues about `Object.wait()` and `Object.notify()` in the model checking mode.

Fix a big in wait/notify processing in model checking

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Options.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Reporter.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/annotations/LogLevel.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTest.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTest.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/EpsilonVerifier.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/LTS.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/SerializabilityVerifier.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/Verifier.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/quiescent/QuiescentConsistencyVerifier.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/StateEquivalenceImplCheckTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/strategy/modelchecking/ModelCheckingOptionsTest.java
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/strategy/stress/StressOptionsTest.java

It is easier for newcomers when you do not need to specify equals/hashCode. Instead, we can print a warning message with an information how to improve the verification performance.

Do not require state equivalance implementation by default

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TraceReporter.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/CapturedValueRepresentationTest.kt

Equal but not same object had the same representation.
For example,
```
field1 = emptyMap()
field2 = emptyMap()
```
was represented in trace as
```
field1.WRITE(HashMap@1)
field2.WRITE(HashMap@1)
```
but should be
```
field1.WRITE(HashMap@1)
field2.WRITE(HashMap@2)
```

Fix equal objects having same representation number

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt

By design, there can be thread switches in `Coroutine.cancel()` method.
However, this caused non-determinism due to not resetting `TestThread.cont` and, as a result, sometimes calling `TestThread.cont.cancel()` when there is no cancellable coroutine, adding odd switch points.

Fix non-determinism due to not resetting TestThread.cont

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/execution/ExecutionResult.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/LincheckFailure.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TracePoint.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/representation/StateRepresentationTest.kt

Execution results were also compared by states.
This is not correct, because we do not require state representations to be deterministic.
The bug showed only when there were incorrect results and non-deterministic state representation was defined.

Fix LinCheck failing when state representation is non-deterministic

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/runner/DeadlockTests.kt

Fixes #125.
LinCheck threw NPE when trying to finish safely after deadlock detection to avoid resource leak.
There was already an internal mechanism to prevent blocking operations after an exception but it was not enabled for Java monitors

Fix NPE when trying to finish after deadlock detection

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Result.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyStateHolder.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/FinalFieldReadingEliminationTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/SerializableValueTests.kt

Fixed a memory leak between iteration in Lincheck.
The LinCheck Verifier caches scenario results which it already verified to bound computations.
However, this cache was kept between different iterations, essentially resulting in a memory leak.
The cached values from previous iterations can be useful only if the scenario generated in the current iteration is the same as in one of the previous iterations, which is an unlikely event in practice.
The size of the leak can be large for tests of reasonable size. I managed to get a 500Mb leak for a configuration with 3 threads, 2 operations per thread, 1000 invocations per iterations and 500 iterations.
This PR re-creates linearizability verifier for each iteration to avoid this leak

Fix Verifier memory leak

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt

Surprisingly, this small change speeds up Lincheck twice.

Optimize internal synchronization

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/WaitNotifyLockTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/test/transformation/WaitNotifyLockTests.kt
src/jvm/test/resources/expected_logs/obstruction_freedom_synchronized.txt

In current implementation of `MonitorTracker` in model checking strategy, the monitor re-entrance information is lost when thread performs `wait` operation on some object. Thus upon wake-up the model checker just re-acquires a monitor once, but does not restore previous monitor re-entrance counter. This leads to a bug (see the new test added in this PR).
This PR fixes this problem by saving the information about lock re-entrance and then correctly restoring it.

Bugfix for wait-notify support in presence of lock re-entrance

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/test/resources/expected_logs/illegal_module_access.txt
src/jvm/test/resources/expected_logs/internal_bug_report.txt

There is a race in `FixedActuveThreadsExecutor` that may lead to a hang. This PR fixes the race and, hopefully, should also fix #194.

Fix a race in FixedActiveThreadsExecutor

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/IllegalModuleAccessOutputMessageTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/InternalLincheckBugTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/util/TestUtils.kt

After #173, `Thread.yield()` and `park()` are called after spinning for a long time. However, this strategy may lead to starvation when the number of parallel threads exceeds the number of cores. As this is a rare case, we can call `yield()` and `park()` immediately on such hardware.

Optimize synchronization when the number of threads exceeds the number of cores

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TracePoint.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TraceReporter.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/TraceReportingTest.kt
src/jvm/test/resources/expected_logs/spin_lock_in_incorrect_results_failure.txt
src/jvm/test/resources/expected_logs/trace_reporting_empty.txt

Currently, empty execution trace is printed incorrectly by the tool as an empty string. 
This PR fixes this. It ensures that at least the executed actors (with their results) are always printed, event if the execution trace does not have any interesting trace points.

Fix representation of empty traces

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/TransformationClassLoader.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/Runner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt

Currently bytecode instrumentation can take significant time. Moreover, it is performed for each scenario even when testing the same data structure. 
In the context of the adaptive planning feature #158, instrumentation time can interfere with the invocations time, thus making it harder to get reliable prediction for the average invocation time. 
This PR provides simple instrumented bytecode caching, thus mitigating the performance overhead of instrumentation.

Bytecode instrumentation cache

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/Runner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/TestThreadExecutionGenerator.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt

We need to unify the init, post, and parallel scenario parts running. Otherwise, it's hard to proceed with #136.

Execute `init` and `post` parts via the same mechanism as for the `parallel` one.

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestStructure.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/CustomScenarioDSL.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Reporter.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/annotations/Validate.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/execution/ExecutionScenario.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/execution/RandomExecutionGenerator.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/InvocationResult.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/Runner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/LincheckFailure.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TraceReporter.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/SerializabilityVerifier.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/quiescent/QuiescentConsistencyVerifier.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/SpinlockEventsCutTests.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ValidationFunctionTests.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/runner/ParallelThreadsRunnerExceptionTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/runner/TestThreadExecutionHelperTest.java
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/util/TestUtils.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/CustomScenarioDSL.kt
src/jvm/test/resources/expected_logs/two_validation_functions_exception.txt
src/jvm/test/resources/expected_logs/validation_function_failure.txt

At most one validation function is allowed

---

README.md
build.gradle.kts
docs/topics/testing-strategies.md
gradle.properties
settings.gradle.kts
src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/test/resources/expected_logs/illegal_module_access.txt

It's easier to test Lincheck on different VM versions using toolchains

Use Gradle toolchain to specify the JDK version

---

build.gradle.kts
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/HangingDetectionTests.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/isolated/DeadlockIsolatedTests.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/isolated/FixedActiveThreadsExecutorIsolatedTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/isolated/ThreadDumpIsolatedTest.kt

Do not call `Thread.stop()` in `FixedActiveThreadsExecutor` on Java 20+

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt

both properties access the current actor id `actorId = currentActorId[iThread]` but do not handle the case when `actorId = -1`, that is the case before any actor has started executing

Fix potential IndexOutOfBoundsException in curActorIsBlocking and concurrentActorCausesBlocking

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/util/Spinner.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/LockFreeSetTest.kt

Tweak constants in `Spinner` to ensure rare `Thread.yield()` calls.

Optimize spin-wait loop in Spinner

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt

On my laptop on `HashMapTest`:
* without the change: ~3.5s
* with the change: ~3.2s

Optimize `TransformationUtils.isCoroutineStateMachineClass` 

---

build.gradle.kts

Now, when running `jvmTest` from IntelliJ IDEA, it includes the `*IsolatedTest` tests, which makes the task extremely slow. We need to be able to run these tests but isolate them somehow. One possible solution is to launch a new JVM instance after N (e.g., 10) tests.

Improve UX when running `*IsolatedTest`s from IntelliJ IDEA

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/LincheckClassLoader.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/CodeInformation.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt

New way of final field detection without `Class.forName`. We need this change for merging transformation via Java agents.

Implement `final` field detection without `Class.forName(..)`

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/util/Spinner.kt

This PR implements optimizes and simplified spin loops:
1. make the counter local variable;
2. count only the number if `spin` calls. 
It also fixes the regression problem on machines with small number of CPUs by changing the `nThreads` parameter of `resultSpinner` to also count for the main thread. If the number of scenario threads + main thread is greater than the number of available CPUs, the main thread does not spin and parks immediately.

Optimize spin loops and fix regression

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt

The #296 update breaks compatibility with the previous plugin versions, so we need to increase the minimum version

Bump minimal plugin version to 0.2

---

build.gradle.kts
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/strategy/modelchecking/LincheckVersionTest.kt

For the plugin version compatibility check, we must know the lincheck version. This is done with 'implementation version' mark in a jar, but in lincheck tests, class files are taken directly from disc. So, for debugging lincheck tests, we pass a system property that contains the version.

Set lincheck version in tests for the plugin compatibility

---

build.gradle.kts
gradle.properties
src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MethodCallTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/AbstractLincheckTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ClocksWithExceptionsInOutputTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ExceptionsInOutputTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/InterleavingAnalysisPresentInSpinCycleFirstIterationTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/InternalLincheckBugTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/TraceReportingTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ValidationFunctionTests.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt

Closes #308
This PR fixes the performance problem accidentally introduced in #296 , that manifested on our Java 11 CI builds. 
The root cause of the problem and the solution are described below. 
The problem was related to the JVM classes re-transformation, performed by the Java agent. 
For model checking instrumentation mode, the class re-transformation was performed lazily on demand. 
However, for the stress strategy, all the loaded classes were re-transformed eagerly for each Lincheck test.
During a long JVM run (e.g. in case of our CI builds), a lot of classes can be loaded to the JVM, and for each Lincheck test run, the Lincheck JVM agent in the stress model would try to re-transform them.
However, for the stress strategy we actually only need to intercept the suspension points, that …

Fix Java 11 performance bug

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/Strategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/runner/ParallelThreadsRunnerExceptionTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/runner/TestThreadExecutionHelperTest.java

This PR proposes a simple refactoring of the `Strategy` class API. 
**Motivation**
Currently, the `Strategy` API provides the following method to run the scenario:
```kotlin
abstract fun run(): LincheckFailure?
```
This method should run the scenario (some) number of times and returns the failure, in case if any invocation fails. 
This API leads to code duplication in the current code base.
* Both stress and model-checking strategies in fact run the scenario fixed number of times in a loop. This loop is duplicated in both implementations. 
* Both strategies run verifier on each invocation result. Again, the implementation of verification method is duplicated in both strategies. 
This PR proposes to change the API, so that the `Strategy` instead provides the method to run single …

Strategy run API refactoring

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/CodeLocations.kt

Fixes #353
I don't know how to create a test here, so let's hope for the best and re-open the issue if it occurs again.

Fix possible `ConcurrentModificationException` when collection information in `FinalFields` and `MethodIds`

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck/ObjectTraverserTest.kt

Avoid recursive enumeration of class and classloader instances when plugin is enabled

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt

In `LincheckJavaAgent`, use `ClassReader.EXPAND_FRAMES` as dictated by the `AnalyzerAdapter` documentation:
> public class **AnalyzerAdapter**
extends [MethodVisitor](https://asm.ow2.io/javadoc/org/objectweb/asm/MethodVisitor.html)
> A [MethodVisitor](https://asm.ow2.io/javadoc/org/objectweb/asm/MethodVisitor.html) that keeps track of stack map frame changes between [visitFrame(int, int, Object[], int, Object[])](https://asm.ow2.io/javadoc/org/objectweb/asm/commons/AnalyzerAdapter.html#visitFrame(int,int,java.lang.Object%5B%5D,int,java.lang.Object%5B%5D)) calls. This adapter must be used with the [ClassReader.EXPAND_FRAMES](https://asm.ow2.io/javadoc/org/objectweb/asm/ClassReader.html#EXPAND_FRAMES) option.
https://asm.ow2.io/javadoc/org/objectweb/asm/commons/AnalyzerAdapter.html

Use `ClassReader.EXPAND_FRAMES` as dictated by the `AnalyzerAdapter` documentation

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt

This PR fixes issue #376 
It implements a quick bug fix specifically for #376, but does not completely solve the root problem described in #419. 
This problem in general is more ubiquitous, requires more complicated changes, and thus would be addressed by a separate PR.
The fix implemented in this PR wraps all methods from `java.lang.StackTraceElement` class into ignored sections. 
This is required due to a combination of two reasons:
1)  `StackTraceElement` own bytecode is not analyzed, but it can call methods from `java.util` (e.g., `HashMap`), which are analyzed by the Lincheck. 
2)  `StackTraceElement` methods can be called almost from any point during execution (e.g., they are called when an exeption is thrown and its stack trace is being collected). 
Thus, in order to ensure that …

Fix of `NoClassDefFoundError` due to unintended Lincheck analysis of `StackTraceElement` methods

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/util/ObjectGraph.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/LocalObjectsTests.kt

This PR changes our approach to the local objects tracking. 
Current approach maintains a map `LocalObject -> List<LocalObject>` , which for each local object stores a list of objects immediately reachable from it (via its fields). This map is used to compute a set of local objects reachable from another given local object. Once a local object is assigned to a field of non-local object, all reachable objects are marked as non-local. 
The problem with this approach is that it is error prone and requires a lot of efforts to maintain the map in the correct state. If the map is not maintained in the correct state, some objects might be incorrectly classified as local (see new test added in this PR). 
So instead, in this PR we implement an alternative approach. We still maintain a *set* of …

Fix local objects detector

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ObjectCreationTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/LocalObjectsTests.kt

Before this PR, `ObjectCreationTransformer` injected `Injections::afterNewObjectCreation` only on the objects on which `Object::<init>` constructor was called. However, if the instrumented code created a new instance of some `Derived` class, such that its `Base` class is not instrumented, then no `Object::<init>` constructor call would be tracked by the current algorithm (since only `Derived::<init>` will be called from the instrumented code).
To fix this issue, we now track any `::<init>` constructor call, and keep a counter of uninitialized objects to distinguish between actual constructor calls, and the calls of the base class constructor from the derived class constructor.

Fix object creation tracking

---

bootstrap/src/sun/nio/ch/lincheck/EventTracker.java
bootstrap/src/sun/nio/ch/lincheck/Injections.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ObjectIdentityHashCodeTracker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ObjectInitialHashCodes.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/InvokeDynamicTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/traceDebugger/AbstractNativeCallTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/traceDebugger/HashCodeTests.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/HashCodeTests.kt

Substitute identity hashcode, received on the first run, on the following runs.

Identity hash code substitution

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TraceReporter.kt

When running my tests I get this error:
```
java.lang.IllegalArgumentException: Count 'n' must be non-negative, but was -5.
at kotlin.text.StringsKt__StringsJVMKt.repeat(StringsJVM.kt:775)
at org.jetbrains.kotlinx.lincheck.strategy.managed.TraceNodePrefixFactory.prefixForNode$lambda$5(TraceReporter.kt:628)
at org.jetbrains.kotlinx.lincheck.strategy.managed.TraceNode.getPrefix(TraceReporter.kt:354)
at org.jetbrains.kotlinx.lincheck.strategy.managed.TraceLeafEvent.addRepresentationTo(TraceReporter.kt:415)
at org.jetbrains.kotlinx.lincheck.strategy.managed.TraceReporterKt.traceGraphToRepresentationList(TraceReporter.kt:343)
at org.jetbrains.kotlinx.lincheck.strategy.managed.TraceReporterKt.appendShortTrace(TraceReporter.kt:43)
at org.jetbrains.kotlinx.lincheck.strategy.managed.TraceReporterKt …
```

Prevent IllegalArgumentException

---

build.gradle.kts
gradle.properties
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/util/TestUtils.kt

Add a flag to automatically overwrite representation tests output.

Automate representation tests repair process

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt

Required by @bbrockbernd in order to test new mutex implementation inside [atomicfu](https://github.com/Kotlin/kotlinx-atomicfu) repository.

Fix atomicfu instrumentation rules (exclude atomics only)

---

src/jvm/test/org/jetbrains/kotlinx/lincheck_test/CoroutinesMultipleSuspensionsTest.kt

Disabled the `CoroutinesMultipleSuspensionsTest.stressTest` test for now, as it is currently flaky on CI. 
Possible reasons could either be:
* The test also requires support of multiple suspension points in the linearizability checker.
* There is some data race in the `ParallelThreadsRunner` class in the code that manages thread suspension statuses.

Ignore flaky coroutines multiple suspensions test

---

docs/topics/constraints.md
docs/topics/introduction.md
docs/topics/operation-arguments.md
docs/topics/progress-guarantees.md
docs/topics/sequential-specification.md
docs/topics/testing-strategies.md

This PR fixes broken links to test samples. For the missing tests, links were removed

fix: broken links to test samples

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/LoopDetector.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/RunConcurrentRepresentationTests.kt
src/jvm/test/resources/expected_logs/run_concurrent_test/atomic_refs.txt

Allow loop detector replayer to continue executing after it finished the replayed part

---

build.gradle.kts
src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Options.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Reporter.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/TraceDebugger.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/annotations/LogLevel.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/util/Logger.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/strategy/modelchecking/ModelCheckingOptionsTest.java
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/strategy/stress/StressOptionsTest.java
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/channel/IncorrectBufferedChannelTest.kt

Partially addresses: #434 
* Simple logger added
* Transformed classes are printed to log file
* How it works:
* One can specify (dev: in `gradle.properties`, lib users in VM arguments) flag `lincheck.log.file` to print log to file (default is `System.err`) 
* Specify flag `lincheck.log.level` to setup logging level (default is a logging level defined in lincheck source code)

Add minimalistic logger to Lincheck

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TracePoint.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TraceReporter.kt

Add date needed for loop visualization in IDEA plugin:
1. Stack trace element data (class, file, line)
2. Internal code locations, which means nothing outside `lincheck`, but have very important property: they are strictly incrementing. It allows to use them to distinguish trace points (and what goes first!) which reside on same line.
This PR change all trace points constructors to hold location Id and not stack trace element, as all of them need location Id now and stack trace element can be derived from location Id.
Please note, that this review contains change of version to make it custom to be able to reference it in plugin. This change should not be merged, of course.

Pass location information of each trace point to IDEA debugger.

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/SnapshotTracker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/util/ThreadMap.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/util/UnsafeHolder.kt

Speeds up `ConcurrentLinkedDequeTest` from 42s to 28s on my local machine

Improve performance by caching some reflection-related data

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt

Without this change, stepping in the plugin does not work

Rollback to make `ideaPluginEnabled` flag lazy

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/TracePoint.kt

Added two entries to the trace communicated from lincheck to the plugin.
- The first is an array of all related types. So for read and write points this is a single type (for example: `[java.lang.Integer]`). For calls the first entry in the array is the return type, the rest are the argument types `[returnType,arg1,arg2]`. (When a call does not have a return type the first entry is empty `[,arg1type,arg2type]`). Additionally when a type is an enum it is prepended with `Enum:`.
- The second added entry is a boolean that is true if a call is static.
Example of a trace element with a function `joe` that takes an `int` and returns an `int`, and is not `static`: `0;0;3;false;-1;joe(15): 16;org/jetbrains/kotlinx/lincheck_test/representation/BobTest:block:BobTest.kt:27;56;[java.lang.Integer,java. …

Additional info in trace sent to plugin for code coloring

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TraceDebuggerAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TraceDebuggerClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MethodCallTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ObjectCreationTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/SharedMemoryAccessTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ThreadTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/util/TestUtils.kt

Currently in the code base two different formats of JVM class names are used: internal and canonical class names. 
Internal class names are primarily used in the `transformation` module in conjunctions with ASM library and other bytecode instrumentation facilities. Other modules of code actively use Java Reflection API and other APIs that expect class names to be given in canonical class names format. 
However, currently in the code base internal class names are leaked from `transformation` module, which sometimes leads to hard-to-spot bugs. 
The solution to the problem is to accept the convention to never leak class names in internal format beyond `transformation` module, and always perform the conversions on the boundaries of `transformation` module. This PR implements this policy. …

Ensure internal class names do not leak from `transformation` module

---

bootstrap/src/sun/nio/ch/lincheck/EventTracker.java
bootstrap/src/sun/nio/ch/lincheck/Injections.java
bootstrap/src/sun/nio/ch/lincheck/ThreadDescriptor.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/ExecutionClassLoader.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/LoopDetector.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyGuarantee.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ConstantHashCodeTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ConstructorArgumentsSnapshotTrackerTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/DeterministicInvokeDynamicTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/LocalVariablesAccessTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MethodCallTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MonitorTransformers.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ObjectCreationTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ParkingTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/SharedMemoryAccessTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/util/AnalysisSections.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/ModelCheckerTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ObstructionFreedomRepresentationTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/RunConcurrentRepresentationTests.kt

This PR contains ignored sections implementation refactoring, needed as a preparation for implementing new silent sections feature: https://github.com/JetBrains/lincheck/issues/501
The most important change is that instead of boolean flag, now a re-entrance depth counter is used to maintain ignored sections information. This provides simpler mental model and API.
Now, instead of:
```java
public static boolean enterIgnoredSection() { ... }
```
we have:
```java
public static void enterIgnoredSection() { ... }
```
Meaning that there is no need to track the result of `enterIgnoredSection()`, wrap `leaveIgnoredSection()` into an `if`, etc. It is sufficient to just call `leaveIgnoredSection()` as many times as was called `enterIgnoredSection()`.
Moreover, now it is possible to write the …

Ignored sections implementation cleanup

---

build.gradle.kts
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/Strategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt

This PR adds a functionality which counts each spin-cycle replay as part of the total invocations count.
Examples of tests, where there is a significant difference between the specified invocations and actual run invocations for ModelChecking regime (among all iterations the biggest difference in invocations is specified):
1. CausesBlockingOperationTest: `15236 / 10000`
1. CyclicBarrierTest: `24162 / 10000`
1. ReentrantLockTest: `2314 / 500`
1. SpinLockTest: `1796 / 500`
1. CoroutineCancelTest::testCancel: `1482 / 100`
1. CoroutineJoinTest: `868 / 100`
1. ReentrantLockSetTest: `3868 / 1000`
... and a couple more tests with a smaller difference
All tests run locally with the same configuration (naive benchmarking, difference could be just an error):
- included spin-cycles replays: `9m 25s` …

Include spin-cycle replays in invocations count 

---

bootstrap/src/sun/nio/ch/lincheck/Injections.java
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/DeterministicInvokeDynamicTransformer.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/CollectorsTest.java

The issue was caused by the fact that `MethodHandles.lookup`, needed for custom handling of invoke-dynamic cannot be called from certain locations. In the case of Java > 8, the only limitation is `java.lang.invoke`, which is fine. While in Java 8 it also includes all Java stdlib packages. So the workaround was to call a private constructor of `MethodHandles` privately with reflection.
The issue was reproducible on one of the tests from Kotlin compiler repository.

Fix the illegal `lookupClass` issue when using `MethodHandles.Lookup` on JDK 8

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt

PR adds some checks that make sure that only test threads (created by the runner) perform manual suspend/resume logic.

Check that only `TestThread`s perform special suspend/resume logic

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt

Now all instrumented classes are processed twice: the first time the class is parsed to ClassNode ("tree") representation to extract local variables info, and the second one it is processed directly by lincheck-specific code visitors with the second call to reader.
This causes two problems:
(1) Labels between these parsings are not preserved and not all local variables information extracted at the first step could be used in the second step.
(2) The same class is parsed twice, which is not effective.
It happens to be that lincheck-specific class visitors can be called directly on tree representation (ClassNode) of class which is obtained on the first step.
It solves both problems.
All tests pass.

Run code transformers against tree class representation.

---

src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/AbstractDeterministicTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/CurrentTimeTests.kt

Tests `ActualTimeMillisTest` and `ActualTimeNanosTest` fail with:
```
= The execution has hung, see the thread dump =
```
instead of normal completion. 
The bug was missed by `AbstractDeterministicTest`. 
This PR fixes the tests by increasing the timeout for them.

Fix timeout in deterministic time tests

---

.idea/runConfigurations/Trace_debugger_Remote.xml
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/tracerecorder/TraceCollectingEventTracker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/tracerecorder/TraceRecorder.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/traceagent/TraceAgentParameters.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/traceagent/TraceRecorderInjections.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracedata/Printing.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracedata/Serialization.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracedata/TraceRecorderTracePoints.kt

Now Agent can take the 4th parameter (after class, method and file): type of output.
Valid values are: `binary`, `text` and `verbose`.
- `binary` is default if no parameter was given or the wrong name was given.
- `text` is simple text output without locations.
- `verbose` is simple text output with locations.
Example of verbose output (double-accesses to arguments looks like Instrumentation problem — local variable `t` is tracked without duplication).
```
GuavaImmutableListTest.list() at :0
GuavaImmutableListTest@990684641.run() at GuavaImmutableListTest.kt:72
t ← Thread@886004375 at GuavaImmutableListTest.kt:58
t → Thread@886004375 at GuavaImmutableListTest.kt:61
Thread@886004375.start() at GuavaImmutableListTest.kt:61
GuavaImmutableListTest@990684641.setY(String@1243350866) at …
```

Add support for human-readable output.

---

build.gradle.kts
src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyConfiguration.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategyConfiguration.kt
src/jvm/main/org/jetbrains/lincheck/datastructures/ModelCheckingStrategyConfiguration.kt

- Explicitly add `jar` to publication dependencies to ensure `.class` files are generated and added to the artifact.
- Fix accidental bug in `runReplayForPlugin` introduced in https://github.com/JetBrains/lincheck/pull/695 during API migration.

Hotfixes for artifact publication and plugin integration

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/traceagent/TraceAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/TraceCollectingEventTracker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/TraceRecorder.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/agent/TraceRecorderInjections.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/agent/TraceRecorderMethodTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/transformers/MethodCallMinimalTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/transformers/ObjectCreationMinimalTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt

It allows to extract it as separate module in the future.

Group all trace-recorder related classes (but not trace data classes) into separate package.

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/LoopDetector.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ValidationFunctionTests.kt

- Fix out-of-bounds exceptions. 
- Effectively disable spin-lock detection inside validation functions (but not total events count check!) --- to support cases of validation functions iterating over large arrays in the concurrent algorithms course.

Hotfixes for livelock detection inside validation function

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/LocalVariablesAccessTransformer.kt

Reads of arguments at source line 0 is compiler-generated checks for nullability and other contracts. Don't show them in trace.
See #722

Don't instrument args reads at code line 0 (#722).

---

src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/TraceCollectingEventTracker.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/InlineMethodCallTransformer.kt

Cannot reproduce a problem with unbalanced calls to call/return.
Add more diagnostics.

Enable inline calls.

---

trace/src/main/org/jetbrains/lincheck/trace/Serialization.kt
trace/src/main/org/jetbrains/lincheck/trace/Streams.kt
trace/src/main/org/jetbrains/lincheck/trace/TraceRecorderTracePoints.kt

Fix problems when thread buffer is overflown.
Limit string size to buffer size, too.
This fix Kotlin's `:compiler:tests-integration:test --tests "org.jetbrains.kotlin.cli.CliTestGenerated$Jvm.testExtraHelp" `
But this test generates 10GiB of Strings, so it will need A LOT of memory to load trace.

Lev serebryakov/tr bugfixes on kotlin tests

---

jvm-agent/src/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt

If we meet a nested class, it will not be properly instrumented without this fix. We will see just a couple of top-level trace points.

Instrument `enclosingClass` of a given class

---

trace/src/main/org/jetbrains/lincheck/trace/TraceRecorderTracePoints.kt

We stumbled upon a bug when `equals` implementation can throw an exception. Because of this we will end up with an exception in `onMethodCallReturn` and incorrect stack in the end.

Compare for `INJECTIONS_VOID_OBJECT` using reference equality

---

jvm-agent/src/main/org/jetbrains/kotlinx/lincheck/trace/agent/TraceAgentParameters.kt

Kotlin function names can contain spaces commas quotes etc which can mess up argument passing.
Parsing is updated to unescape everything that is escaped and properly split the string into args.
It is backwards compatible aka without escaping logic it should work normally.

Support character escaping for args passed to javaagent

---

common/src/main/org/jetbrains/lincheck/util/Reflection.kt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.collections.immutable/tests.contract.list.ImmutableListTest_empty.txt
jvm-agent/src/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/SnapshotTracker.kt
trace-debugger/src/main/org/jetbrains/lincheck/trace/debugger/TraceDebuggerInjections.kt
trace-recorder/src/main/org/jetbrains/lincheck/trace/recorder/TraceCollectingEventTracker.kt

Traversing and transforming all static field (and reachable objects) in each call to `ensureClassHierarchyIsTransformed` is not necessary. 
We need to transform only the value read from a static field.

Minimize the static field traversals during lazy re-transformation 

---

bootstrap/src/sun/nio/ch/lincheck/EventTracker.java
bootstrap/src/sun/nio/ch/lincheck/Injections.java
bootstrap/src/sun/nio/ch/lincheck/ThreadDescriptor.java
buildSrc/src/main/kotlin/TraceAgentIntegrationTestsTasks.kt
common/src/main/org/jetbrains/lincheck/trace/TraceContext.kt
common/src/main/org/jetbrains/lincheck/util/AnalysisSections.kt
common/src/main/org/jetbrains/lincheck/util/Spinner.kt
integration-test/trace-recorder/src/main/org/jetbrains/trace/recorder/test/KotlinCoroutinesTraceRecorderIntegrationTest.kt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.coroutines/kotlinx.coroutines.DelayJvmTest_testDelayInArbitraryContext.txt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.coroutines/kotlinx.coroutines.EventLoopsTest_testEventLoopInDefaultExecutor.txt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.coroutines/kotlinx.coroutines.ExecutorsTest_testDefaultDispatcherToExecutor.txt
jvm-agent/src/main/org/jetbrains/lincheck/jvm/agent/transformers/InlineMethodCallTransformer.kt
jvm-agent/src/main/org/jetbrains/lincheck/jvm/agent/transformers/IntrinsicCandidateMethodFilter.kt
jvm-agent/src/main/org/jetbrains/lincheck/jvm/agent/transformers/MethodCallMinimalTransformer.kt
jvm-agent/src/main/org/jetbrains/lincheck/jvm/agent/transformers/MethodCallTransformer.kt
jvm-agent/src/main/org/jetbrains/lincheck/jvm/agent/transformers/ThreadTransformer.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/FixedActiveThreadsExecutor.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/ThreadScheduler.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
trace-recorder/src/main/org/jetbrains/lincheck/trace/recorder/TraceCollectingEventTracker.kt
trace-recorder/src/main/org/jetbrains/lincheck/trace/recorder/TraceRecorder.kt
trace-recorder/src/main/org/jetbrains/lincheck/trace/recorder/TraceRecorderInjections.kt
trace/src/main/org/jetbrains/lincheck/trace/Printing.kt
trace/src/main/org/jetbrains/lincheck/trace/Serialization.kt
trace/src/main/org/jetbrains/lincheck/trace/SerializationCommon.kt
trace/src/main/org/jetbrains/lincheck/trace/TRTracePointPrinters.kt
trace/src/main/org/jetbrains/lincheck/trace/TracePostprocessor.kt
trace/src/main/org/jetbrains/lincheck/trace/TraceRecorderTracePoints.kt

TODO:
PR in the plugin: https://jetbrains.team/p/concurrency-tools/reviews/106/files

Add support for all-threads tracking

---

integration-test/trace-recorder/build.gradle.kts
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.coroutines/kotlinx.coroutines.EventLoopsTest_testEventLoopInDefaultExecutor.txt

The PR ensures that extended integration tests run even if the basic ones fail.

Ensure all integration tests run

---

common/src/main/org/jetbrains/lincheck/trace/TraceContext.kt
integration-test/trace-recorder/src/main/resources/integrationTestData/TraceDebuggerExamples/org.examples.hackathon.SimpleProgramNonFailingTest_test.txt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.collections.immutable/tests.contract.list.ImmutableListTest_empty.txt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.collections.immutable/tests.contract.list.ImmutableListTest_empty_with_exclude_filter.txt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.collections.immutable/tests.contract.list.ImmutableListTest_empty_with_include_filter.txt
integration-test/trace-recorder/src/main/resources/integrationTestData/kotlinx.coroutines/kotlinx.coroutines.ExecutorsTest_testDefaultDispatcherToExecutor.txt
trace/src/main/org/jetbrains/lincheck/trace/Deserialization.kt
trace/src/main/org/jetbrains/lincheck/trace/Serialization.kt
trace/src/main/org/jetbrains/lincheck/trace/SerializationCommon.kt
trace/src/main/org/jetbrains/lincheck/trace/TRTracePointPrinters.kt
trace/src/main/org/jetbrains/lincheck/trace/TraceRecorderTracePoints.kt

see [DR-311](https://youtrack.jetbrains.com/issue/DR-311) Apply owner name trace prettifying to method arguments
- Serialize and deserialize codelocation arguments
- Show method call arguments in trace
- For primitives `name -> value`
- For objects `name`
- When name is not available we default to original behaviour

Argument names for method calls (DR-311)

---

common/src/main/org/jetbrains/lincheck/util/AnalysisSections.kt
src/jvm/main/org/jetbrains/kotlinx/lincheck/trace/TraceFlattenPolicies.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/ThrowableTest.kt
src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/MethodReportingTest.kt
src/jvm/test/resources/expected_logs/method_reporting.txt
src/jvm/test/resources/expected_logs/method_reporting_trace_debugger.txt

TLDR: `Throwable` has `suspend` methods and thus should be instrumented by Licnheck to intercept monitor events and guarantee correct thread scheduling.
Consider `synchronzied` methods `Throwable::addSuppressed` and `Throwable::cause`.
Consider a scenario when these two methods are called concurrently.
Without additional measures, the deadlock can happen in the following way:
- thread 1 will acquire monitor on `addSuppressed`;
- internally `addSuppressed` will call `ArrayList::add` method;
- this method could be instrumented, and if so it will call one of Lincheck injections;
- this injection can decide to block the thread and switch to thread 2;
- thread 2 will attempt to acquire monitor on `cause`;
- this will deadlock with thread 1.
To prevent this deadlock, Lincheck should ensure that …

Fix possible deadlock involving `Throwable`

---

bootstrap/src/sun/nio/ch/lincheck/Injections.java
common/src/main/org/jetbrains/lincheck/util/AnalysisSections.kt
trace-recorder/src/main/org/jetbrains/lincheck/trace/recorder/TraceRecorder.kt

When the main thread finishes and disables analysis in all other running threads, we need to ensure that we do not register any more threads in `EventTracker::registerRunningThread`

Disable global threads descriptors creation on the trace end
