JetBrains/lincheck

- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/CTestStructure.java
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/OperationsInAbstractClassTest.kt
> Support declarations of operations, global parameters, and operation groups in parent classes

- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
There was a memory leak since the internal cache of methods ```methodsCache``` was specified as ```WeakHashMap<Class<*>, HashMap<Method, Method>>```.
Unfortunately, ```WeakHashMap``` cannot delete a key if there is a strong reference from the corresponding value to it. Since methods have references to their classes, the keys cannot be deleted; that produces a memory leak.
Using ```WeakHashMap<Class<*>, WeakHashMap<Method, WeakReference<Method>>>``` fixes the problem.
> Memory leak in method caching fixed

- lincheck/pom.xml
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Actor.kt
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/CTestStructure.java
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/CancellabilitySupportTransformer.kt
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Result.kt
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/TransformationClassLoader.java
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/Utils.kt
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/annotations/Operation.java
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/execution/ActorGenerator.java
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/runner/TestThreadExecutionGenerator.java
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.java
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/LTS.kt
- lincheck/src/main/java/org/jetbrains/kotlinx/lincheck/verifier/linearizability/LinearizabilityVerifier.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/AlmostEmptyScenarioTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/HangingTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/NonParallelOpGroupTest.java
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/OperationsInAbstractClassTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/runner/ParallelThreadsRunnerEasyExceptionTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/runner/TestThreadExecutionHelperTest.java
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/CustomScenarioDSL.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/BufferedChannelCustomTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/BufferedChannelStressTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/RendezvousChannelCustomTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/RendezvousChannelStressTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/ResumingFollowUpTest.kt
- lincheck/src/test/java/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/SequentialIntChannel.kt
- pom.xml
> Cancellation support

- src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
Due to recursion in scenario minimization previously objects could not be garbage collected, causing `OutOfMemoryError`
> Fixed OutOfMemoryError when minimizing scenario

- README.md
- src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestConfiguration.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/CustomScenarioDSL.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/Options.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedCTestConfiguration.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTestConfiguration.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingOptions.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressCTestConfiguration.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/stress/StressOptions.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/CustomScenarioDSLTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/runner/ResumingFollowUpTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/verifier/CustomScenarioDSL.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/verifier/linearizability/LockFreeSetTest.kt
A feature to generate custom scenarios with DSL builder and to run tests on them.
DSL scenario generation:
```kotlin
scenario {
initial {
actor(SPMCQueue::offer, 1)
actor(SPMCQueue::offer, 2)
}
parallel {
thread {
elements.forEach { actor(SPMCQueue::offer, it) }
}
thread {
repeat(5) {
actor(SPMCQueue::poll)
}
}
}
}
```
> Custom scenario DSL

- docs/cfg/buildprofiles.xml
To work the Edit page button on the website properly
> fix: fix property for Edit page button

- README.md
- docs/topics/constraints.md
- docs/topics/introduction.md
- docs/topics/operation-arguments.md
- docs/topics/progress-guarantees.md
- docs/topics/sequential-specification.md
- docs/topics/testing-strategies.md
- docs/v.list
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/guide/BasicCounterTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/guide/ConcurrentLinkedDequeTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/guide/ConcurrentMapTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/guide/CounterTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck/test/guide/ObstructionFreedomViolationTest.kt
Hi, I read the [lincheck-guide](https://kotlinlang.org/docs/lincheck-guide.html) and noticed some minor problems. Most of them were missing imports and one non working example (didn't fail as specified).
Please have a look and let me know if any changes are needed.
> example guide - minor cleanup

- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyTransformer.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/HashCodeTests.kt
> Fix hashCode() support

- src/jvm/main/org/jetbrains/kotlinx/lincheck/Actor.kt
On my laptop on `HashMapTest`:
* without the change: ~3.5s
* with the change: ~1.9s
> Optimize Method.isSuspendable implementation

- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/FaaQueueTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/MinimizationTests.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/isolated/ThreadDumpIsolatedTest.kt
> Increase number of invocations for flaky stress tests

- src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/util/AtomicMethods.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/util/ObjectGraph.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/util/UnsafeHolder.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/ObjectTraverserTest.kt
- Adds a utility function for proper object graph traversing and rewrites all places where such functionality was used
- Fixes #402
> Utility function for unified object hierarchy traversing

- src/jvm/main/org/jetbrains/kotlinx/lincheck/Reporter.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/execution/ExecutionResult.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/AbstractLincheckTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/ExceptionTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/util/TestUtils.kt
> Fix internal Lincheck bug check

- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/ExceptionTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/IncorrectOnCancellationTest.kt
* remove flaky `ExceptionTest`
* increase the number of interleavings in flaky `IncorrectOnCancellationTest`
> Fix some flaky tests

- src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingCTestConfiguration.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt
This is simple refactoring PR, does not change the functionality.
> Move Intellij plugin related functionality into `IdeaPlugin.kt`

- src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/Lincheck.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ObjectLabelFactory.kt
> Update the `IdeaPlugin.kt` API on the Lincheck side for general-purpose model checking

- src/jvm/main/org/jetbrains/kotlinx/lincheck/Lincheck.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/CountDownLatchTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/CyclicBarrierTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/DaemonThreadPoolTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/PrintingTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/coroutines/BaseCoroutineTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/coroutines/CoroutineCancelTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/coroutines/CoroutineJoinTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/RunConcurrentRepresentationTests.kt
Extracted non-channel tests from PR: https://github.com/JetBrains/lincheck/pull/531
> Add new tests with gpmc & coroutines

- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategyGuarantee.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/PrintingTest.kt
> Fix hanging problems with standard streams

- build.gradle.kts
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/InterruptionTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/UserThreadExceptionTest.kt
> Finish user thread when exception is throw from it

- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/ConstructorArgumentsSnapshotTrackerTransformer.kt
Improve the code style of the specified class
> Refactor ConstructorArgumentsSnapshotTrackerTransformer

- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
Small refactoring that closes #592
> Decouple trace points creation from switch points creation

- src/jvm/main/org/jetbrains/kotlinx/lincheck/IdeaPlugin.kt
Fix few typos introduced during the refactoring https://github.com/JetBrains/lincheck/pull/600
> Fix Idea plugin integration bugs 

- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/LoopDetector.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
Small refactoring to clarify code in `ManagedStrategy::newSwitchPoint()`
> Refactor loop detector should switch method call

- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/LoopDetector.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/trace/TraceCollector.kt
Small refactoring that is required to simplify the trace collection
> Move `TraceCollector` into a separate file

- src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/util/ObjectGraph.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/datastructures/LockFreeTaskQueue.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/quiescent/LockFreeTaskQueueTest.kt
Partly resolves https://github.com/JetBrains/lincheck/issues/601
> Remove all `INVISIBLE_REFERENCE` suppressions

- src/jvm/main/org/jetbrains/kotlinx/lincheck/Lincheck.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/CountDownLatchTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/CyclicBarrierTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/IntrinsicCandidateMethodTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/JavaAPITest.java
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/KotlinAPITest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/PrintingTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/UserThreadExceptionTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/coroutines/BaseCoroutineTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/coroutines/CoroutinesDelayTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/gpmc/coroutines/DaemonThreadPoolTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/RunConcurrentRepresentationTests.kt
> Finalize the GPMC API

- bootstrap/src/sun/nio/ch/lincheck/EventTracker.java
- bootstrap/src/sun/nio/ch/lincheck/Injections.java
- bootstrap/src/sun/nio/ch/lincheck/Types.java
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/MethodCallResultsTracker.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/DeterministicMethodDescriptor.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/DeterministicRandomMethodDescriptor.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/PureDeterministicMethodDescriptor.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/ReplayableMutableInstance.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/io/DeterministicFileMethodDescriptor.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/io/FileApiSpecificMethodDescriptors.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/io/ForEachHolder.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/io/JavaStandardLibrary.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/io/TrackedIterable.java
- src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/native_calls/io/TrackedIterator.java
- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MethodCallTransformer.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/util/AnalysisSections.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/util/Reflection.kt
- src/jvm/test-jdk11/org/jetbrains/kotlinx/lincheck_test/trace_debugger/io/FileSpecialCasesOnModernJdksTests.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/AbstractDeterministicTest.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/io/FileSpecialCasesTests.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/io/FileTests.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/io/StreamTests.kt
- src/jvm/test/org/jetbrains/kotlinx/lincheck_test/trace_debugger/io/ZipStreamTests.kt
- src/jvm/test/resources/expected_logs/run_concurrent_test/main_thread_blocked_trace_debugger_jdk11.txt
Trace debugger support for file/directory-related API excluding `java.nio.Channel`-related
> Support java.io, java.nio.file in trace debugger

- src/jvm/main/org/jetbrains/kotlinx/lincheck/tracerecorder/TraceCollectingEventTracker.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt
> Fix multithread recording (692)

- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassFileTransformer.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
Small refactoring to simplify future development.
> Extract `LincheckClassFileTransformer` into separate file

- src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/VerifierState.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/linearizability/LinearizabilityVerifier.kt
- src/jvm/main/org/jetbrains/kotlinx/lincheck/verifier/quiescent/QuiescentConsistencyVerifier.kt
> Deprecated `org.jetbrains.kotlinx.lincheck` verifiers for backward compatibility

- RELEASE.md
- build.gradle.kts
A few final tweaks in the sonatype publication configuration.
> Sonatype publishing leftovers

- trace-recorder/src/main/org/jetbrains/lincheck/trace/recorder/TraceCollectingEventTracker.kt
solves [DR-280](https://youtrack.jetbrains.com/issue/DR-280) Stackoverflow on IJ Ultimate test
> [Bugfix] stackoverflow trace recorder
